# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6aa3052a2aed4a78417db72e949b097720e89f235f32a6ffa810f120fc3b6bf357fcbdac143a3b7833b495cba654acffae5e1ecb39fc7aed2641a1d968866ef1

test:
  secret_key_base: 1f07595ac14a915908e86b0d837901de37ad0c0140ace6b80906d6a987237cf541bf9199dd38afeba29387008ac8cb7a5a9b0a10ff97c3607c2b3e28ce6db8fe

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
